# Generated by Django 4.2.19 on 2025-04-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], default='ожидается оплата', max_length=40, verbose_name='Статус оплаты'),
        ),
    ]
