# Generated by Django 5.2a1 on 2025-03-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tables',
        ),
        migrations.AddField(
            model_name='event',
            name='table',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendarapp.tables'),
        ),
        migrations.AddField(
            model_name='event',
            name='total_cost',
            field=models.FloatField(default=300),
        ),
        migrations.AddField(
            model_name='event',
            name='total_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tables',
            name='table_description',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
