# Generated by Django 5.2a1 on 2025-03-01 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_event_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tables',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendarapp.tables'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='number',
            field=models.IntegerField(choices=[(1, 'Стол 1'), (2, 'Стол 2')], unique=True),
        ),
    ]
