# Generated by Django 4.2.19 on 2025-04-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_tempbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='payment_status',
        ),
    ]
