# Generated by Django 5.2a1 on 2025-02-23 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_event_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='table_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
            preserve_default=False,
        ),
    ]
