# Generated by Django 5.2a1 on 2025-03-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_alter_event_tables_alter_tables_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tables',
            new_name='table',
        ),
    ]
