# Generated by Django 5.2a1 on 2025-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_event_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='table_number',
        ),
        migrations.AddField(
            model_name='event',
            name='tables',
            field=models.ManyToManyField(related_name='events', to='calendarapp.tables'),
        ),
    ]
