# Generated by Django 4.2.19 on 2025-03-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_rename_tables_event_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='table_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
