# Generated by Django 5.2a1 on 2025-02-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_tables_remove_event_table_number_event_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tables',
            options={'verbose_name': 'Стол', 'verbose_name_plural': 'Столы'},
        ),
        migrations.AlterField(
            model_name='tables',
            name='number',
            field=models.IntegerField(choices=[(1, 'Стол 1'), (2, 'Стол 2'), (3, 'Стол 3'), (4, 'Стол 4')], unique=True),
        ),
        migrations.AlterField(
            model_name='tables',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=6),
        ),
    ]
