# Generated by Django 4.2.19 on 2025-03-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_tables_table_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='table_description',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
