# Generated by Django 4.2.19 on 2025-04-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_event_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='tables',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
    ]
