# Generated by Django 4.2.19 on 2025-03-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_alter_tables_table_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cost',
            new_name='totalcost',
        ),
        migrations.AlterField(
            model_name='tables',
            name='number',
            field=models.IntegerField(choices=[(1, 'Стол 1'), (2, 'Стол 2'), (3, 'Стол 3'), (4, 'Стол 4')], unique=True),
        ),
    ]
