# Generated by Django 5.2a1 on 2025-02-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_alter_tables_options_alter_tables_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='price_per_half_hour',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=6),
        ),
    ]
