# Generated by Django 4.2.19 on 2025-04-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_tables_cancel_reason_tables_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='is_canceled',
        ),
        migrations.AddField(
            model_name='event',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
    ]
