# Generated by Django 4.2.19 on 2025-03-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_rename_cost_event_totalcost_alter_tables_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='totalcost',
            new_name='total_cost',
        ),
    ]
