# Generated by Django 4.2.19 on 2025-03-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_rename_totalcost_event_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total_cost',
            field=models.FloatField(default=300),
        ),
    ]
