# Generated by Django 5.1.8 on 2025-05-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_remove_tables_cancel_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('number_of_events', models.PositiveIntegerField(default=4, verbose_name='количество посещений')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
    ]
