# Generated by Django 5.1.8 on 2025-05-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_remove_tables_cancel_reason_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempBooking',
        ),
    ]
