# Generated by Django 5.1.8 on 2025-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
