# Generated by Django 5.1.8 on 2025-05-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0011_alter_tables_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
